### ISSUE TITLE
长时间运行到前台，native heap越来越大

### ISSUE THREAD

**Issue by ChloeDimen** [zhushenwudi/serialport#1]
protected native void finalize();的作用是什么？
我碰到一种情况，app长时间运行在前台，app的memory会越来越大，直到app奔溃。
我查看是native heap越来越大。nativeSerialPort是要保存C++类的地址（由于usb串口不稳，串口地址会改变，所以会扫描地址重新打开新的串口地址），怀疑会持续申请内存。

**Comment by zhushenwudi** [comment]
你好，很高兴看到有人在使用我的库，目前我已经把cpp层的代码放到了仓库里，具体finalize的实现可以下载最新的代码审查。目前我这面测试到，只要串口正常读取的话，是不会导致heap越来越大的，具体有什么试验表明的话，请贴图在下面。
